#!/usr/bin/env python

import sys


if __name__ == "__main__":
    dump = open("/tmp/austerus-core-test-log", "w")

    line = True

    while line:
        line = sys.stdin.readline()
        dump.write("IN: ")
        dump.write(line)
        dump.flush()

        if len(line) == 0:
            continue

        if line == "\n":
            continue

        if line.startswith("#"):
            continue

        if line.startswith(";"):
            continue

        else:
            sys.stdout.write("ok\n")
            dump.write("OUT: ")
            dump.write("ok\n")
            dump.flush()

        sys.stdout.flush()

    dump.close()

